version: '3.8'

services:
    php-apache:
        env_file:
            - .env
        container_name: "${CONTAINER_NAME_PREFIX}-php-apache"
        build:
            dockerfile: ./docker/php-apache/Dockerfile
        #extra_hosts REQUIRED in Linux for xdebug!!
        extra_hosts:
            - host.docker.internal:host-gateway
        ####
        volumes:
            - ${PATH_TO_SYMFONY_PROJECT}:/var/www/html
            - ${APACHE_LOG_DIR}:/etc/apache2/${APACHE_LOG_DIR}
        ports:
            - "80:80"
            - "443:443"
        networks:
            - symfony
    mariadb:
        env_file:
            - .env
        container_name: "${CONTAINER_NAME_PREFIX}-mariadb"
        image: mariadb:11.1.4
        volumes:
            - ${PATH_TO_DB_DATA}:/var/lib/mysql:rw
            - ./docker/mariadb/mariadb.cnf:/etc/mysql/my.cnf
            # CUSTOM Users Script to add your users (optional)
            #- ./docker/mariadb/config/users.sql:/docker-entrypoint-initdb.d/users.sql
        environment:
            - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD}
            - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=0
            #  - MARIADB_USER=${DB_USER}
            #  - MARIADB_PASSWORD=${DB_PASSWORD}
            - MARIADB_DATABASE=${DB_NAME}
        ports:
            - "3306:3306"
        networks:
            - symfony
#    mailer:
#        env_file:
#            - .env
#        container_name: "${CONTAINER_NAME_PREFIX}-mailer"
#        image: schickling/mailcatcher
#        ports:
#            - "1025:1025"
#            - "1080:1080"
#        networks:
#            - symfony
#    adminer:
#        env_file:
#            - .env
#        container_name: "${CONTAINER_NAME_PREFIX}-adminer"
#        image: adminer
#        ports:
#            - "8080:8080"
#        networks:
#            - symfony
networks:
    symfony: