<?php

/**
 * View script for selecting the bank
 */

use NeoApp\frontend\PaymentInitiation\LocaleQuery;

/** @var \Neo_View $this */

$this->layout()->setLayout('tailwind');

/** @var \NeoApp\frontend\PaymentInitiation\Dto\DefaultResponseParams $response */
$response = $this->response;

$currentCountryIso = $response->countryIso;
$currentLang = $response->languageCode;
$locales = [
    'countries' => $response->availableLocales->countries,
    'languages' => $response->availableLocales->languages,
];
$transactionToken = $response->transactionToken;

/** @var \Neo\Gateway\Processor\PaymentInitiation\Dto\AbstractPaymentSummary $paymentSummary */
$paymentSummary = $this->paymentSummary;

/** @var string $localeServiceUrl */
$localeServiceUrl = $this->localeServiceUrl;

$widgetTexts = [
    'cancel' => $this->translate('Cancel'),
    'location_preferences' => $this->translate('Location preferences'),
    'save' => $this->translate('Confirm'),
    'country' => $this->translate('Country'),
    'language' => $this->translate('Language'),
];

$bankUiTexts = [
    'search_placeholder' => $this->translate('Search your bank'),
    'no_results' => $this->translate('No results for your search'),
    'recommended' => $this->translate('Recommended'),
    'all_banks' => $this->translate('All banks'),
    'sort_by' => $this->translate('Sort by'),
    'az' => $this->translate('AZ'),
    'za' => $this->translate('ZA'),
    'change_location' => $this->translate('Bank not listed?') . ' ' . $this->translate('Try another country'),
    'another_payment_method' => $this->translate('Choose another payment method'),
    'load_more' => $this->translate('Load more banks'),
];

$cancelAction = 'authorize-payment-cancel?errorCode=' . Neo_ErrorCodes_Neo::TWO_STEPS_SALE_TRANSACTION_INTERRUPTED_BY_USER;

$providersDescriptions = $this->providersDescriptions;
$bankListData = [
    'banks' => $providersDescriptions,
    'translations' => $bankUiTexts,
];

if (Neo_Model_PaymentMethod::SEPA == $paymentSummary->subscriptionPaymentMethodId) {
    $formTitle = 'Securely Link to Your Bank for Protected Payments.';
} else {
    $formTitle = 'First time using Pay by Bank?';
}

$FOOTER_FIXED = 'partials/v2/components/footer-fixed.phtml';
$FOOTER_BLOCK = 'partials/v2/components/footer-block.phtml';
?>

<style>
    .disclaimer {
        font-size: 14px;
        padding: 1rem 0;
        color: #969696;
        display: flex;
        gap: 0.5rem;
    }

    .disclaimer:has(.errors) {
        display: block;
    }

    .errors {
        color: red;
    }

    .disclaimer a,
    a.switchPaymentMethod {
        text-decoration: underline;
    }

    #pi_bank_code,
    #pi_bank_code-label,
    #pi_bank_code-element,
    #pi_consent-label {
        visibility: hidden;
        display: none;
    }

    #pi_consent-element {
        display: flex;
        gap: 0.25rem;
    }

    #pi-select-provider-form dd,
    #pi-select-provider-form dt {
        margin: 0;
        padding: 0;
    }
</style>

<div id="local_overlay"
    class="hidden justify-center items-center fixed top-0 left-0 w-full h-dvh bg-white/90 dark:bg-black/90 z-[999] duration-150 ease-in-out">
    <div class="spinner animate-spin"></div>
</div>

<main class="grid grid-cols-12">
    <section class="fe-grid-left-sidebar">
        <div class="w-full md:w-full lg:w-9/12 xl:w-3/5 flex flex-col justify-between relative">
            <header class="flex items-center justify-between mx-0 gap-4">
                <?= $this->partial('partials/v2/components/site-title.phtml', $this); ?>

                <language-selector
                    data="<?= htmlspecialchars(json_encode($locales)) ?>"
                    translations="<?= htmlspecialchars(json_encode($widgetTexts)) ?>"
                    lang="<?= $currentLang ?>"
                    endpoint="<?= $localeServiceUrl ?>"
                    country=<?= $currentCountryIso ?>>
                </language-selector>

            </header>

            <div class="hidden md:block">
                <?= $this->partial($FOOTER_FIXED, $this); ?>
            </div>
        </div>
    </section>

    <section class="fe-grid-right-sidebar">
        <div class="w-full md:w-full lg:w-9/12 xl:w-3/5 min-h-[60vh] mr-auto">
            <div class="flex justify-between mb-5">
                <a class=" px-3 py-2 font-semibold rounded-lg border dark:border-zinc-500 dark:text-zinc-200"
                    href="authorize-payment-cancel?errorCode=<?= Neo_ErrorCodes_Neo::TWO_STEPS_SALE_TRANSACTION_INTERRUPTED_BY_USER ?>"><?= $widgetTexts['cancel'] ?></a>
            </div>

            <div id="firstTimeMessage" class='max-w-full mt-8 border rounded-xl p-5'>
                <h2 class='font-bold text-2xl text-deepTurquoise-500 dark:text-deepTurquoise-200 mb-2 mr-10'><?= $this->translate($formTitle) ?></h2>
                <p class='mb-2 text-zinc-600 dark:text-zinc-200'>
                    <?= $this->translate('Pay securely from your bank account - no cards needed.') ?>
                    <?= $this->translate('Your bank will not share any personal information with us.') ?>
                </p>

                <div class='bg-deepTurquoise-500 dark:bg-deepTurquoise-700 rounded-xl p-5 box-border'>
                    <h4 class="font-bold text-lg text-white">
                        <?= $this->translate('How it works') ?>
                    </h4>
                    <ol class="space-y-2 text-white">
                        <li class="flex gap-2">
                            <span class="size-7 rounded-full bg-coral-500 dark:bg-coral-700 text-black flex flex-wrap items-center justify-center text-center">1</span>
                            <p class="flex-1">
                                <?= $this->translate('Select your bank.') ?>
                            </p>
                        </li>
                        <li class="flex gap-2">
                            <span class="size-7 rounded-full bg-coral-500 dark:bg-coral-700 text-black flex flex-wrap items-center justify-center text-center">2</span>
                            <p class="flex-1">
                                <?= $this->translate('You\'ll be redirected to your bank\'s secure site or app.') ?>
                            </p>
                        </li>
                        <li class="flex gap-2">
                            <span class="size-7 rounded-full bg-coral-500 dark:bg-coral-700 text-black flex flex-wrap items-center justify-center text-center">3</span>
                            <p class="flex-1">
                                <?= $this->translate('Log in and approve the payment.') ?>
                            </p>
                        </li>
                        <li class="flex gap-2">
                            <span class="size-7 rounded-full bg-coral-500 dark:bg-coral-700 text-black flex flex-wrap items-center justify-center text-center">4</span>
                            <p class="flex-1">
                                <?= $this->translate('Enjoy your purchase!') ?>
                            </p>
                        </li>
                    </ol>
                </div>

                <button onClick="hideMessage()" class="border rounded px-2 py-1 mt-2"><?= $this->translate('Got it!') ?></button>
            </div>


            <h2 class="font-bold text-xl mb-2 mt-8 dark:text-zinc-200"><?= $this->translate('Choose your bank') ?></h2>
            <bank-search-list id="bankSearch" data="<?= htmlspecialchars(json_encode($bankListData)) ?>"></bank-search-list>
            <form id="pi-select-provider-form" method="post" action="pi-widget?token=<?= $transactionToken ?>">
                <?= $this->form->getElement('pi_bank_code') ?>

                <?php if ($paymentSummary->isConsentStringRequired): ?>
                    <div class="disclaimer">
                        <?= $this->form->getElement('pi_consent') ?>
                        <div>
                            <?= $this->partial('partials/' . $paymentSummary->gatewayName . '-consent-string.phtml', ['paymentSummary' => $paymentSummary]) ?>
                            ;
                        </div>
                    </div>
                <?php endif; ?>
                <?= $this->form->getElement('csrf_token') ?>
            </form>
        </div>
    </section>
</main>
<div class="block md:hidden dark:bg-zinc-900">
    <?= $this->partial($FOOTER_BLOCK, $this); ?>
</div>

<script src="<?= $this->cdnUrl('/common/components/language-selector.Ce6ShMJw.umd.js') ?>"></script>
<script src="<?= $this->cdnUrl('/common/components/bank-search-list.BFyCzJiI.umd.js') ?>"></script>
<script>
    const bankForm = document.getElementById('pi-select-provider-form');
    const overlay = document.querySelector('#local_overlay');
    // Event listener for the language update
    document.addEventListener('language-update', () => {
        overlay.classList.remove('hidden');
        overlay.classList.add('flex');
        window.location.reload();
    })

    document.addEventListener('change-payment-method', () => {
        window.location.href = '<?= $cancelAction ?>';
    })

    // This function is called when a bank is selected
    function onSelectBank(bankCode) {
        overlay.classList.remove('hidden');
        overlay.classList.add('flex');
        document.getElementById('pi_bank_code').value = bankCode;
        bankForm.submit();
    }

    function hideMessage() {
        const message = document.getElementById('firstTimeMessage');
        message.classList.add('hidden');
    }fon

    customElements.whenDefined('bank-search-list').then(() => {
        const bankSearch = document.getElementById('bankSearch');
        bankSearch.onSelectBank = onSelectBank;
    });
</script>
