kafka:
  clusters:
    - name: local
      bootstrapServers: kafka:29092
      schemaRegistry: http://schema-registry:8081
#      kafkaConnect:
#        - name: connect-local
#          address: http://connect:8083
