on:
  pull_request:
    types: [opened, synchronize]

jobs:
  code_review_job:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
    - name: AI Code Review
      uses: freeedcom/ai-codereviewer@main
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_API_MODEL: "gpt-3.5-turbo"
        exclude: "**/*.json,**/*.md"
